### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by martinferianc** [corerain/papaa18-tutorial#10]
#### Tutorial 1:
- [ ] Access Graph Contents: this could be marked as optional because there is an overlap with tutorial 2
#### Tutorial 2: 
- [ ] Plumber installation could be a problem, it was for Ringo the instructions need to be tested
- [ ] Explain what is plumber little bit more in depth what exactly does it do
- [ ] Introduce this repo: https://github.com/ringochu/TensorFlowDemo about how to use tensorflow, python in case someone needs a refresher.

**Comment by kumasento** [comment]
Hi Martin,

Thanks for your and Ringo's efforts. These suggestions look great. Only the
first suggestion for tutorial 2 may not be quite urgent, since each
attender to our tutorial will have an environment with pre-installed
plumber.

For the rest, I think it is definitely worthwhile to make some changes
based on them.

Best regards,
Vincent

**Comment by aksenventwo** [comment]
Hi Martin, Thanks for you  and Ringo's suggestions.

### For Turorial 1
You need to understand the contents of **Access Graph Contents** before you can continue with tutorial 2, tutorial 2 is based on tutorial 1, and tutorial 2 does not explain tensorflow and other related things. Tutorial 2 is just an introduction to `DFG IR`. So this part of the content may not be suitable as an option. 

### For Turorial 2

1. Vincent has explained that Plumber is pre-installed and can be used directly.
2. Yes, we should introduce Plumebr first, I ignored this, thank you very much for your suggestion.
3. Looks good, but this may need to be at the end of tutorial 1.

**Comment by martinferianc** [comment]
Hi @kumasento and @aksenventwo thanks for replies. I wanted to ask how much do we need to change individually to also incorporate suggestions of Professor Luk, resp. I am a bit confused what is going to be our final final structure and whether our toolchain has all the capabilities that were suggested to show, what should I personally change for tutorial 3 then?

**Comment by aksenventwo** [comment]
Hi @martinferianc，I am not sure as well.
